import { Button, VerticalBox } from "std-widgets.slint";
import {Global_1, Global_2} from "all_globals.slint";

export {Global_1, Global_2}

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
     }
}
